name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby dependencies
        run: bundle install

      - name: Setup database
        run: bin/rails db:test:prepare

      - name: Run tests
        run: bin/rails test

  deploy:
    needs: test
    runs-on: self-hosted
    environment: staging
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kamal
        run: gem install kamal

      - name: Kamal Deploy
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_USERNAME: ${{ secrets.TELEGRAM_CHANNEL_USERNAME }}
          TELEGRAM_BOT_NAME: ${{ secrets.TELEGRAM_BOT_NAME }}
        run: kamal deploy

      - name: Kamal Clean
        run: kamal prune all
